/********************************************************************************
** Form generated from reading UI file 'ControllerFrameEx.ui'
**
** Created by: Qt User Interface Compiler version 5.8.0
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_CONTROLLERFRAMEEX_H
#define UI_CONTROLLERFRAMEEX_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QCheckBox>
#include <QtWidgets/QComboBox>
#include <QtWidgets/QGroupBox>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QListWidget>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QRadioButton>
#include <QtWidgets/QSpinBox>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QTabWidget>
#include <QtWidgets/QTableWidget>
#include <QtWidgets/QToolBar>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_ControllerFrameEx
{
public:
    QWidget *centralWidget;
    QTableWidget *tableWidget;
    QGroupBox *groupBox;
    QRadioButton *zoneRadio1;
    QRadioButton *zoneRadio2;
    QSpinBox *zoneNumberSetter;
    QLabel *label;
    QGroupBox *groupBox_2;
    QCheckBox *autoCRole;
    QCheckBox *autoLogin;
    QComboBox *charaComboBox;
    QLabel *label_6;
    QSpinBox *charaNumberSetter;
    QPushButton *pathSelectBTN;
    QLineEdit *gamePathEditor;
    QGroupBox *groupBox_6;
    QPushButton *readBtn1;
    QPushButton *readBtn2;
    QPushButton *readBtn3;
    QPushButton *readBtn4;
    QPushButton *readBtn5;
    QPushButton *readBtn6;
    QPushButton *writeBtn2;
    QPushButton *writeBtn4;
    QPushButton *writeBtn5;
    QPushButton *writeBtn3;
    QPushButton *writeBtn1;
    QPushButton *writeBtn6;
    QPushButton *baseConfigBtn;
    QTabWidget *tabWidget_3;
    QWidget *tab_10;
    QGroupBox *groupBox_3;
    QTabWidget *tabWidget;
    QWidget *tab;
    QSpinBox *open_lag;
    QLabel *openLag;
    QSpinBox *windowCounter;
    QLabel *label_2;
    QPushButton *onePunch;
    QPushButton *engineBtn;
    QCheckBox *EnginedBox;
    QWidget *tab_2;
    QPushButton *generalEnd;
    QPushButton *forceEnd;
    QLabel *label_61;
    QLabel *timeLabel;
    QLabel *label_7;
    QGroupBox *groupBox_4;
    QTabWidget *defaultTab;
    QWidget *tab_6;
    QCheckBox *isZhuxianEnableBox;
    QCheckBox *captainBox;
    QCheckBox *huoliProtectBox;
    QCheckBox *buqianBox;
    QSpinBox *duimoSpinBox;
    QCheckBox *junziShiyongBox;
    QCheckBox *shimenYongjunBox;
    QSpinBox *manhuoSpinBox;
    QLabel *label_71;
    QLabel *label_9;
    QLineEdit *forceIdField;
    QLabel *label_10;
    QSpinBox *timeLimitSpinBox;
    QLabel *label_11;
    QLabel *label_12;
    QSpinBox *mitanCounterSpinBox;
    QLabel *label_13;
    QSpinBox *levelSpinBox;
    QLabel *label_14;
    QSpinBox *shimenCounterSpinBox;
    QCheckBox *huoyueCheckBox;
    QCheckBox *generalDZCheckBox;
    QWidget *tab_7;
    QGroupBox *groupBox_7;
    QRadioButton *mengyanRadio1;
    QRadioButton *mengyanRadio2;
    QGroupBox *groupBox_8;
    QRadioButton *jiandingRadio1;
    QRadioButton *jiandingRadio2;
    QGroupBox *groupBox_9;
    QRadioButton *jiandingRadio1_2;
    QRadioButton *jiandingRadio2_2;
    QGroupBox *groupBox_10;
    QRadioButton *qicaiRadio1;
    QRadioButton *qicaiRadio2;
    QWidget *tab_8;
    QWidget *tab_9;
    QComboBox *saoComboBox;
    QLineEdit *goldController;
    QLabel *label_3;
    QLabel *label_4;
    QLineEdit *safeJunzi;
    QLabel *label_5;
    QSpinBox *saoPointer;
    QWidget *tab_11;
    QTabWidget *tabWidget_5;
    QWidget *tab_15;
    QCheckBox *rizuanBox;
    QCheckBox *yuezuanBox;
    QCheckBox *liuyaoBox;
    QWidget *tab_16;
    QWidget *tab_3;
    QGroupBox *groupBox_5;
    QListWidget *scriptSortList;
    QTabWidget *tabWidget_2;
    QWidget *tab_4;
    QPushButton *guaitiBtn;
    QPushButton *xiangshiBtn;
    QPushButton *mitanBtn;
    QPushButton *shimenBtn;
    QPushButton *wuxingBtn;
    QPushButton *chumoBtn;
    QPushButton *zhufuBtn;
    QPushButton *shiliBtn;
    QPushButton *wuwaBtn;
    QPushButton *kuaimaBtn;
    QPushButton *mijingBtn;
    QPushButton *tianlaoBtn;
    QPushButton *biwuBtn;
    QPushButton *xiaoyaoBtn;
    QPushButton *yanwuBtn;
    QPushButton *tianweiBtn;
    QPushButton *jingjiBtn;
    QPushButton *huoliXiangyaoBtn;
    QPushButton *huoliHuangquanBtn;
    QPushButton *huoliHudieBtn;
    QPushButton *huoliCanglangBtn;
    QPushButton *juediBtn;
    QPushButton *wanshengBtn;
    QPushButton *guaguaBtn;
    QPushButton *yunshiBtn;
    QPushButton *huoliWeijiBtn;
    QPushButton *huoliJingjiiBtn;
    QPushButton *huoliWuxingBtn;
    QWidget *tab_5;
    QPushButton *dengsaoBtn;
    QPushButton *shangjiaBtn;
    QPushButton *xuanquBtn;
    QPushButton *xiajiaBtn;
    QPushButton *qingbaoBtn;
    QPushButton *pingbiBtn;
    QPushButton *huoyueLingJiangBtn;
    QPushButton *xiuliBtn;
    QPushButton *shengjiBtn;
    QPushButton *jiadianBtn;
    QPushButton *lingyouBtn;
    QPushButton *shengmaBtn;
    QPushButton *tongjiCailiaoBtn;
    QPushButton *lingFuliBtn;
    QPushButton *jinHJunBtn;
    QPushButton *sahuoBtn;
    QPushButton *cuncangBtn;
    QPushButton *chongwuShoumingBtn;
    QPushButton *powerCheckBtn;
    QPushButton *joinForceBtn;
    QPushButton *jiaoxueqiuBtn;
    QPushButton *embededScriptBtn;
    QPushButton *kaibaoBtn;
    QWidget *tab_12;
    QPushButton *goldCalculate;
    QLineEdit *test;
    QPushButton *shengdanBtn;
    QLineEdit *idField;
    QPushButton *scriptUp;
    QPushButton *scriptDown;
    QPushButton *scriptDelete;
    QPushButton *scriptClear;
    QGroupBox *groupBox_11;
    QListWidget *subScriptSortList;
    QPushButton *scriptClear_2;
    QPushButton *scriptDown_2;
    QPushButton *scriptDelete_2;
    QPushButton *scriptUp_2;
    QTabWidget *tabWidget_4;
    QWidget *tab_13;
    QPushButton *zuduiBtn;
    QPushButton *jiaoyouBtn;
    QPushButton *alineBtn;
    QPushButton *teamMitanbtn;
    QPushButton *teamPatabtn;
    QWidget *tab_14;
    QGroupBox *groupBox_12;
    QCheckBox *checkBox;
    QSpinBox *teamSpinBox;
    QLabel *label_8;
    QMenuBar *menuBar;
    QToolBar *mainToolBar;
    QStatusBar *statusBar;

    void setupUi(QMainWindow *ControllerFrameEx)
    {
        if (ControllerFrameEx->objectName().isEmpty())
            ControllerFrameEx->setObjectName(QStringLiteral("ControllerFrameEx"));
        ControllerFrameEx->resize(1075, 620);
        centralWidget = new QWidget(ControllerFrameEx);
        centralWidget->setObjectName(QStringLiteral("centralWidget"));
        tableWidget = new QTableWidget(centralWidget);
        tableWidget->setObjectName(QStringLiteral("tableWidget"));
        tableWidget->setGeometry(QRect(10, 20, 651, 431));
        tableWidget->setRowCount(0);
        tableWidget->setColumnCount(0);
        groupBox = new QGroupBox(centralWidget);
        groupBox->setObjectName(QStringLiteral("groupBox"));
        groupBox->setGeometry(QRect(10, 460, 131, 111));
        zoneRadio1 = new QRadioButton(groupBox);
        zoneRadio1->setObjectName(QStringLiteral("zoneRadio1"));
        zoneRadio1->setEnabled(true);
        zoneRadio1->setGeometry(QRect(20, 30, 51, 16));
        zoneRadio1->setChecked(false);
        zoneRadio2 = new QRadioButton(groupBox);
        zoneRadio2->setObjectName(QStringLiteral("zoneRadio2"));
        zoneRadio2->setEnabled(true);
        zoneRadio2->setGeometry(QRect(80, 30, 51, 16));
        zoneRadio2->setChecked(true);
        zoneNumberSetter = new QSpinBox(groupBox);
        zoneNumberSetter->setObjectName(QStringLiteral("zoneNumberSetter"));
        zoneNumberSetter->setGeometry(QRect(20, 60, 42, 22));
        label = new QLabel(groupBox);
        label->setObjectName(QStringLiteral("label"));
        label->setGeometry(QRect(70, 60, 54, 21));
        groupBox_2 = new QGroupBox(centralWidget);
        groupBox_2->setObjectName(QStringLiteral("groupBox_2"));
        groupBox_2->setGeometry(QRect(180, 460, 421, 71));
        autoCRole = new QCheckBox(groupBox_2);
        autoCRole->setObjectName(QStringLiteral("autoCRole"));
        autoCRole->setGeometry(QRect(20, 20, 101, 16));
        autoCRole->setChecked(true);
        autoLogin = new QCheckBox(groupBox_2);
        autoLogin->setObjectName(QStringLiteral("autoLogin"));
        autoLogin->setGeometry(QRect(20, 40, 91, 16));
        autoLogin->setChecked(true);
        charaComboBox = new QComboBox(groupBox_2);
        charaComboBox->setObjectName(QStringLiteral("charaComboBox"));
        charaComboBox->setGeometry(QRect(120, 26, 69, 20));
        label_6 = new QLabel(groupBox_2);
        label_6->setObjectName(QStringLiteral("label_6"));
        label_6->setGeometry(QRect(210, 30, 81, 16));
        charaNumberSetter = new QSpinBox(groupBox_2);
        charaNumberSetter->setObjectName(QStringLiteral("charaNumberSetter"));
        charaNumberSetter->setGeometry(QRect(310, 30, 42, 22));
        charaNumberSetter->setMinimum(1);
        charaNumberSetter->setMaximum(10);
        charaNumberSetter->setValue(10);
        pathSelectBTN = new QPushButton(centralWidget);
        pathSelectBTN->setObjectName(QStringLiteral("pathSelectBTN"));
        pathSelectBTN->setGeometry(QRect(180, 540, 75, 23));
        gamePathEditor = new QLineEdit(centralWidget);
        gamePathEditor->setObjectName(QStringLiteral("gamePathEditor"));
        gamePathEditor->setGeometry(QRect(280, 540, 321, 20));
        gamePathEditor->setReadOnly(true);
        groupBox_6 = new QGroupBox(centralWidget);
        groupBox_6->setObjectName(QStringLiteral("groupBox_6"));
        groupBox_6->setGeometry(QRect(630, 470, 441, 91));
        readBtn1 = new QPushButton(groupBox_6);
        readBtn1->setObjectName(QStringLiteral("readBtn1"));
        readBtn1->setGeometry(QRect(70, 20, 51, 23));
        readBtn2 = new QPushButton(groupBox_6);
        readBtn2->setObjectName(QStringLiteral("readBtn2"));
        readBtn2->setGeometry(QRect(130, 20, 51, 23));
        readBtn3 = new QPushButton(groupBox_6);
        readBtn3->setObjectName(QStringLiteral("readBtn3"));
        readBtn3->setGeometry(QRect(190, 20, 51, 23));
        readBtn4 = new QPushButton(groupBox_6);
        readBtn4->setObjectName(QStringLiteral("readBtn4"));
        readBtn4->setGeometry(QRect(250, 20, 51, 23));
        readBtn5 = new QPushButton(groupBox_6);
        readBtn5->setObjectName(QStringLiteral("readBtn5"));
        readBtn5->setGeometry(QRect(310, 20, 51, 23));
        readBtn6 = new QPushButton(groupBox_6);
        readBtn6->setObjectName(QStringLiteral("readBtn6"));
        readBtn6->setGeometry(QRect(370, 20, 51, 23));
        writeBtn2 = new QPushButton(groupBox_6);
        writeBtn2->setObjectName(QStringLiteral("writeBtn2"));
        writeBtn2->setGeometry(QRect(130, 50, 51, 23));
        writeBtn4 = new QPushButton(groupBox_6);
        writeBtn4->setObjectName(QStringLiteral("writeBtn4"));
        writeBtn4->setGeometry(QRect(250, 50, 51, 23));
        writeBtn5 = new QPushButton(groupBox_6);
        writeBtn5->setObjectName(QStringLiteral("writeBtn5"));
        writeBtn5->setGeometry(QRect(310, 50, 51, 23));
        writeBtn3 = new QPushButton(groupBox_6);
        writeBtn3->setObjectName(QStringLiteral("writeBtn3"));
        writeBtn3->setGeometry(QRect(190, 50, 51, 23));
        writeBtn1 = new QPushButton(groupBox_6);
        writeBtn1->setObjectName(QStringLiteral("writeBtn1"));
        writeBtn1->setGeometry(QRect(70, 50, 51, 23));
        writeBtn6 = new QPushButton(groupBox_6);
        writeBtn6->setObjectName(QStringLiteral("writeBtn6"));
        writeBtn6->setGeometry(QRect(370, 50, 51, 23));
        baseConfigBtn = new QPushButton(groupBox_6);
        baseConfigBtn->setObjectName(QStringLiteral("baseConfigBtn"));
        baseConfigBtn->setGeometry(QRect(20, 20, 41, 51));
        baseConfigBtn->setAutoRepeat(false);
        baseConfigBtn->setAutoExclusive(false);
        tabWidget_3 = new QTabWidget(centralWidget);
        tabWidget_3->setObjectName(QStringLiteral("tabWidget_3"));
        tabWidget_3->setGeometry(QRect(670, 10, 401, 441));
        tab_10 = new QWidget();
        tab_10->setObjectName(QStringLiteral("tab_10"));
        groupBox_3 = new QGroupBox(tab_10);
        groupBox_3->setObjectName(QStringLiteral("groupBox_3"));
        groupBox_3->setGeometry(QRect(0, 10, 171, 241));
        tabWidget = new QTabWidget(groupBox_3);
        tabWidget->setObjectName(QStringLiteral("tabWidget"));
        tabWidget->setGeometry(QRect(10, 60, 151, 151));
        tab = new QWidget();
        tab->setObjectName(QStringLiteral("tab"));
        open_lag = new QSpinBox(tab);
        open_lag->setObjectName(QStringLiteral("open_lag"));
        open_lag->setGeometry(QRect(90, 40, 42, 22));
        open_lag->setMinimum(6);
        open_lag->setValue(10);
        openLag = new QLabel(tab);
        openLag->setObjectName(QStringLiteral("openLag"));
        openLag->setGeometry(QRect(0, 40, 81, 16));
        windowCounter = new QSpinBox(tab);
        windowCounter->setObjectName(QStringLiteral("windowCounter"));
        windowCounter->setGeometry(QRect(90, 10, 42, 22));
        label_2 = new QLabel(tab);
        label_2->setObjectName(QStringLiteral("label_2"));
        label_2->setGeometry(QRect(0, 10, 81, 16));
        onePunch = new QPushButton(tab);
        onePunch->setObjectName(QStringLiteral("onePunch"));
        onePunch->setGeometry(QRect(0, 70, 61, 23));
        engineBtn = new QPushButton(tab);
        engineBtn->setObjectName(QStringLiteral("engineBtn"));
        engineBtn->setGeometry(QRect(84, 70, 61, 23));
        EnginedBox = new QCheckBox(tab);
        EnginedBox->setObjectName(QStringLiteral("EnginedBox"));
        EnginedBox->setGeometry(QRect(20, 100, 81, 16));
        EnginedBox->setChecked(true);
        tabWidget->addTab(tab, QString());
        tab_2 = new QWidget();
        tab_2->setObjectName(QStringLiteral("tab_2"));
        tabWidget->addTab(tab_2, QString());
        generalEnd = new QPushButton(groupBox_3);
        generalEnd->setObjectName(QStringLiteral("generalEnd"));
        generalEnd->setGeometry(QRect(10, 210, 61, 23));
        forceEnd = new QPushButton(groupBox_3);
        forceEnd->setObjectName(QStringLiteral("forceEnd"));
        forceEnd->setGeometry(QRect(90, 210, 61, 23));
        label_61 = new QLabel(groupBox_3);
        label_61->setObjectName(QStringLiteral("label_61"));
        label_61->setGeometry(QRect(20, 30, 54, 12));
        timeLabel = new QLabel(groupBox_3);
        timeLabel->setObjectName(QStringLiteral("timeLabel"));
        timeLabel->setGeometry(QRect(80, 25, 41, 21));
        label_7 = new QLabel(groupBox_3);
        label_7->setObjectName(QStringLiteral("label_7"));
        label_7->setGeometry(QRect(140, 20, 31, 31));
        groupBox_4 = new QGroupBox(tab_10);
        groupBox_4->setObjectName(QStringLiteral("groupBox_4"));
        groupBox_4->setGeometry(QRect(180, 10, 201, 401));
        defaultTab = new QTabWidget(groupBox_4);
        defaultTab->setObjectName(QStringLiteral("defaultTab"));
        defaultTab->setGeometry(QRect(10, 20, 181, 371));
        tab_6 = new QWidget();
        tab_6->setObjectName(QStringLiteral("tab_6"));
        isZhuxianEnableBox = new QCheckBox(tab_6);
        isZhuxianEnableBox->setObjectName(QStringLiteral("isZhuxianEnableBox"));
        isZhuxianEnableBox->setGeometry(QRect(10, 10, 71, 16));
        isZhuxianEnableBox->setChecked(true);
        captainBox = new QCheckBox(tab_6);
        captainBox->setObjectName(QStringLiteral("captainBox"));
        captainBox->setGeometry(QRect(10, 30, 71, 16));
        huoliProtectBox = new QCheckBox(tab_6);
        huoliProtectBox->setObjectName(QStringLiteral("huoliProtectBox"));
        huoliProtectBox->setGeometry(QRect(10, 50, 71, 16));
        huoliProtectBox->setCheckable(false);
        buqianBox = new QCheckBox(tab_6);
        buqianBox->setObjectName(QStringLiteral("buqianBox"));
        buqianBox->setGeometry(QRect(10, 70, 71, 16));
        buqianBox->setCheckable(false);
        duimoSpinBox = new QSpinBox(tab_6);
        duimoSpinBox->setObjectName(QStringLiteral("duimoSpinBox"));
        duimoSpinBox->setGeometry(QRect(80, 30, 42, 22));
        junziShiyongBox = new QCheckBox(tab_6);
        junziShiyongBox->setObjectName(QStringLiteral("junziShiyongBox"));
        junziShiyongBox->setGeometry(QRect(10, 90, 71, 16));
        shimenYongjunBox = new QCheckBox(tab_6);
        shimenYongjunBox->setObjectName(QStringLiteral("shimenYongjunBox"));
        shimenYongjunBox->setGeometry(QRect(10, 110, 91, 16));
        manhuoSpinBox = new QSpinBox(tab_6);
        manhuoSpinBox->setObjectName(QStringLiteral("manhuoSpinBox"));
        manhuoSpinBox->setGeometry(QRect(90, 130, 42, 22));
        manhuoSpinBox->setMinimum(0);
        manhuoSpinBox->setMaximum(200);
        manhuoSpinBox->setValue(100);
        label_71 = new QLabel(tab_6);
        label_71->setObjectName(QStringLiteral("label_71"));
        label_71->setGeometry(QRect(10, 130, 54, 21));
        label_9 = new QLabel(tab_6);
        label_9->setObjectName(QStringLiteral("label_9"));
        label_9->setGeometry(QRect(10, 160, 54, 12));
        forceIdField = new QLineEdit(tab_6);
        forceIdField->setObjectName(QStringLiteral("forceIdField"));
        forceIdField->setGeometry(QRect(60, 156, 91, 20));
        label_10 = new QLabel(tab_6);
        label_10->setObjectName(QStringLiteral("label_10"));
        label_10->setGeometry(QRect(10, 180, 54, 21));
        timeLimitSpinBox = new QSpinBox(tab_6);
        timeLimitSpinBox->setObjectName(QStringLiteral("timeLimitSpinBox"));
        timeLimitSpinBox->setGeometry(QRect(80, 180, 42, 22));
        timeLimitSpinBox->setMaximum(500);
        timeLimitSpinBox->setValue(150);
        label_11 = new QLabel(tab_6);
        label_11->setObjectName(QStringLiteral("label_11"));
        label_11->setGeometry(QRect(140, 175, 31, 31));
        label_12 = new QLabel(tab_6);
        label_12->setObjectName(QStringLiteral("label_12"));
        label_12->setGeometry(QRect(10, 210, 81, 16));
        mitanCounterSpinBox = new QSpinBox(tab_6);
        mitanCounterSpinBox->setObjectName(QStringLiteral("mitanCounterSpinBox"));
        mitanCounterSpinBox->setGeometry(QRect(90, 210, 42, 22));
        mitanCounterSpinBox->setMinimum(50);
        mitanCounterSpinBox->setMaximum(500);
        mitanCounterSpinBox->setValue(100);
        label_13 = new QLabel(tab_6);
        label_13->setObjectName(QStringLiteral("label_13"));
        label_13->setGeometry(QRect(10, 240, 81, 21));
        levelSpinBox = new QSpinBox(tab_6);
        levelSpinBox->setObjectName(QStringLiteral("levelSpinBox"));
        levelSpinBox->setGeometry(QRect(90, 240, 42, 22));
        levelSpinBox->setMinimum(35);
        levelSpinBox->setMaximum(100);
        levelSpinBox->setValue(35);
        label_14 = new QLabel(tab_6);
        label_14->setObjectName(QStringLiteral("label_14"));
        label_14->setGeometry(QRect(10, 270, 81, 21));
        shimenCounterSpinBox = new QSpinBox(tab_6);
        shimenCounterSpinBox->setObjectName(QStringLiteral("shimenCounterSpinBox"));
        shimenCounterSpinBox->setGeometry(QRect(90, 270, 42, 22));
        shimenCounterSpinBox->setMinimum(10);
        shimenCounterSpinBox->setMaximum(100);
        shimenCounterSpinBox->setValue(50);
        huoyueCheckBox = new QCheckBox(tab_6);
        huoyueCheckBox->setObjectName(QStringLiteral("huoyueCheckBox"));
        huoyueCheckBox->setGeometry(QRect(10, 300, 91, 16));
        generalDZCheckBox = new QCheckBox(tab_6);
        generalDZCheckBox->setObjectName(QStringLiteral("generalDZCheckBox"));
        generalDZCheckBox->setGeometry(QRect(10, 320, 91, 16));
        defaultTab->addTab(tab_6, QString());
        tab_7 = new QWidget();
        tab_7->setObjectName(QStringLiteral("tab_7"));
        groupBox_7 = new QGroupBox(tab_7);
        groupBox_7->setObjectName(QStringLiteral("groupBox_7"));
        groupBox_7->setGeometry(QRect(20, 10, 151, 41));
        mengyanRadio1 = new QRadioButton(groupBox_7);
        mengyanRadio1->setObjectName(QStringLiteral("mengyanRadio1"));
        mengyanRadio1->setGeometry(QRect(10, 20, 61, 16));
        mengyanRadio2 = new QRadioButton(groupBox_7);
        mengyanRadio2->setObjectName(QStringLiteral("mengyanRadio2"));
        mengyanRadio2->setGeometry(QRect(80, 20, 61, 16));
        mengyanRadio2->setChecked(true);
        groupBox_8 = new QGroupBox(tab_7);
        groupBox_8->setObjectName(QStringLiteral("groupBox_8"));
        groupBox_8->setGeometry(QRect(20, 50, 151, 41));
        jiandingRadio1 = new QRadioButton(groupBox_8);
        jiandingRadio1->setObjectName(QStringLiteral("jiandingRadio1"));
        jiandingRadio1->setGeometry(QRect(10, 20, 61, 16));
        jiandingRadio2 = new QRadioButton(groupBox_8);
        jiandingRadio2->setObjectName(QStringLiteral("jiandingRadio2"));
        jiandingRadio2->setGeometry(QRect(80, 20, 61, 16));
        jiandingRadio2->setChecked(true);
        groupBox_9 = new QGroupBox(groupBox_8);
        groupBox_9->setObjectName(QStringLiteral("groupBox_9"));
        groupBox_9->setGeometry(QRect(0, 0, 151, 41));
        jiandingRadio1_2 = new QRadioButton(groupBox_9);
        jiandingRadio1_2->setObjectName(QStringLiteral("jiandingRadio1_2"));
        jiandingRadio1_2->setGeometry(QRect(10, 20, 61, 16));
        jiandingRadio2_2 = new QRadioButton(groupBox_9);
        jiandingRadio2_2->setObjectName(QStringLiteral("jiandingRadio2_2"));
        jiandingRadio2_2->setGeometry(QRect(80, 20, 61, 16));
        jiandingRadio2_2->setChecked(true);
        groupBox_10 = new QGroupBox(tab_7);
        groupBox_10->setObjectName(QStringLiteral("groupBox_10"));
        groupBox_10->setGeometry(QRect(20, 90, 151, 41));
        qicaiRadio1 = new QRadioButton(groupBox_10);
        qicaiRadio1->setObjectName(QStringLiteral("qicaiRadio1"));
        qicaiRadio1->setGeometry(QRect(10, 20, 61, 16));
        qicaiRadio2 = new QRadioButton(groupBox_10);
        qicaiRadio2->setObjectName(QStringLiteral("qicaiRadio2"));
        qicaiRadio2->setGeometry(QRect(80, 20, 61, 16));
        qicaiRadio2->setChecked(true);
        defaultTab->addTab(tab_7, QString());
        tab_8 = new QWidget();
        tab_8->setObjectName(QStringLiteral("tab_8"));
        defaultTab->addTab(tab_8, QString());
        tab_9 = new QWidget();
        tab_9->setObjectName(QStringLiteral("tab_9"));
        saoComboBox = new QComboBox(tab_9);
        saoComboBox->setObjectName(QStringLiteral("saoComboBox"));
        saoComboBox->setGeometry(QRect(20, 10, 91, 16));
        goldController = new QLineEdit(tab_9);
        goldController->setObjectName(QStringLiteral("goldController"));
        goldController->setGeometry(QRect(110, 40, 61, 20));
        label_3 = new QLabel(tab_9);
        label_3->setObjectName(QStringLiteral("label_3"));
        label_3->setGeometry(QRect(20, 40, 91, 16));
        label_4 = new QLabel(tab_9);
        label_4->setObjectName(QStringLiteral("label_4"));
        label_4->setGeometry(QRect(20, 70, 81, 16));
        safeJunzi = new QLineEdit(tab_9);
        safeJunzi->setObjectName(QStringLiteral("safeJunzi"));
        safeJunzi->setGeometry(QRect(110, 70, 61, 20));
        label_5 = new QLabel(tab_9);
        label_5->setObjectName(QStringLiteral("label_5"));
        label_5->setGeometry(QRect(20, 100, 54, 12));
        saoPointer = new QSpinBox(tab_9);
        saoPointer->setObjectName(QStringLiteral("saoPointer"));
        saoPointer->setGeometry(QRect(110, 100, 42, 22));
        saoPointer->setValue(4);
        defaultTab->addTab(tab_9, QString());
        tabWidget_3->addTab(tab_10, QString());
        tab_11 = new QWidget();
        tab_11->setObjectName(QStringLiteral("tab_11"));
        tabWidget_5 = new QTabWidget(tab_11);
        tabWidget_5->setObjectName(QStringLiteral("tabWidget_5"));
        tabWidget_5->setGeometry(QRect(10, 20, 371, 381));
        tab_15 = new QWidget();
        tab_15->setObjectName(QStringLiteral("tab_15"));
        rizuanBox = new QCheckBox(tab_15);
        rizuanBox->setObjectName(QStringLiteral("rizuanBox"));
        rizuanBox->setGeometry(QRect(10, 10, 51, 16));
        rizuanBox->setChecked(true);
        yuezuanBox = new QCheckBox(tab_15);
        yuezuanBox->setObjectName(QStringLiteral("yuezuanBox"));
        yuezuanBox->setGeometry(QRect(10, 30, 51, 16));
        yuezuanBox->setChecked(true);
        liuyaoBox = new QCheckBox(tab_15);
        liuyaoBox->setObjectName(QStringLiteral("liuyaoBox"));
        liuyaoBox->setGeometry(QRect(10, 50, 51, 16));
        liuyaoBox->setChecked(true);
        tabWidget_5->addTab(tab_15, QString());
        tab_16 = new QWidget();
        tab_16->setObjectName(QStringLiteral("tab_16"));
        tabWidget_5->addTab(tab_16, QString());
        tabWidget_3->addTab(tab_11, QString());
        tab_3 = new QWidget();
        tab_3->setObjectName(QStringLiteral("tab_3"));
        groupBox_5 = new QGroupBox(tab_3);
        groupBox_5->setObjectName(QStringLiteral("groupBox_5"));
        groupBox_5->setGeometry(QRect(10, 10, 381, 201));
        scriptSortList = new QListWidget(groupBox_5);
        scriptSortList->setObjectName(QStringLiteral("scriptSortList"));
        scriptSortList->setGeometry(QRect(10, 20, 81, 161));
        tabWidget_2 = new QTabWidget(groupBox_5);
        tabWidget_2->setObjectName(QStringLiteral("tabWidget_2"));
        tabWidget_2->setGeometry(QRect(120, 20, 231, 171));
        tab_4 = new QWidget();
        tab_4->setObjectName(QStringLiteral("tab_4"));
        guaitiBtn = new QPushButton(tab_4);
        guaitiBtn->setObjectName(QStringLiteral("guaitiBtn"));
        guaitiBtn->setGeometry(QRect(0, 0, 41, 23));
        xiangshiBtn = new QPushButton(tab_4);
        xiangshiBtn->setObjectName(QStringLiteral("xiangshiBtn"));
        xiangshiBtn->setGeometry(QRect(0, 22, 41, 21));
        mitanBtn = new QPushButton(tab_4);
        mitanBtn->setObjectName(QStringLiteral("mitanBtn"));
        mitanBtn->setGeometry(QRect(0, 40, 41, 23));
        shimenBtn = new QPushButton(tab_4);
        shimenBtn->setObjectName(QStringLiteral("shimenBtn"));
        shimenBtn->setGeometry(QRect(0, 60, 41, 23));
        wuxingBtn = new QPushButton(tab_4);
        wuxingBtn->setObjectName(QStringLiteral("wuxingBtn"));
        wuxingBtn->setGeometry(QRect(0, 80, 41, 23));
        chumoBtn = new QPushButton(tab_4);
        chumoBtn->setObjectName(QStringLiteral("chumoBtn"));
        chumoBtn->setGeometry(QRect(0, 100, 41, 23));
        zhufuBtn = new QPushButton(tab_4);
        zhufuBtn->setObjectName(QStringLiteral("zhufuBtn"));
        zhufuBtn->setGeometry(QRect(0, 120, 41, 23));
        shiliBtn = new QPushButton(tab_4);
        shiliBtn->setObjectName(QStringLiteral("shiliBtn"));
        shiliBtn->setGeometry(QRect(40, 0, 41, 23));
        wuwaBtn = new QPushButton(tab_4);
        wuwaBtn->setObjectName(QStringLiteral("wuwaBtn"));
        wuwaBtn->setGeometry(QRect(40, 20, 41, 23));
        kuaimaBtn = new QPushButton(tab_4);
        kuaimaBtn->setObjectName(QStringLiteral("kuaimaBtn"));
        kuaimaBtn->setGeometry(QRect(40, 40, 41, 23));
        mijingBtn = new QPushButton(tab_4);
        mijingBtn->setObjectName(QStringLiteral("mijingBtn"));
        mijingBtn->setGeometry(QRect(40, 60, 41, 23));
        tianlaoBtn = new QPushButton(tab_4);
        tianlaoBtn->setObjectName(QStringLiteral("tianlaoBtn"));
        tianlaoBtn->setGeometry(QRect(40, 80, 41, 23));
        biwuBtn = new QPushButton(tab_4);
        biwuBtn->setObjectName(QStringLiteral("biwuBtn"));
        biwuBtn->setGeometry(QRect(40, 100, 41, 23));
        xiaoyaoBtn = new QPushButton(tab_4);
        xiaoyaoBtn->setObjectName(QStringLiteral("xiaoyaoBtn"));
        xiaoyaoBtn->setGeometry(QRect(40, 120, 41, 23));
        yanwuBtn = new QPushButton(tab_4);
        yanwuBtn->setObjectName(QStringLiteral("yanwuBtn"));
        yanwuBtn->setGeometry(QRect(80, 0, 41, 23));
        tianweiBtn = new QPushButton(tab_4);
        tianweiBtn->setObjectName(QStringLiteral("tianweiBtn"));
        tianweiBtn->setGeometry(QRect(80, 20, 41, 23));
        jingjiBtn = new QPushButton(tab_4);
        jingjiBtn->setObjectName(QStringLiteral("jingjiBtn"));
        jingjiBtn->setGeometry(QRect(80, 40, 41, 23));
        huoliXiangyaoBtn = new QPushButton(tab_4);
        huoliXiangyaoBtn->setObjectName(QStringLiteral("huoliXiangyaoBtn"));
        huoliXiangyaoBtn->setGeometry(QRect(80, 60, 41, 23));
        huoliHuangquanBtn = new QPushButton(tab_4);
        huoliHuangquanBtn->setObjectName(QStringLiteral("huoliHuangquanBtn"));
        huoliHuangquanBtn->setGeometry(QRect(80, 80, 41, 23));
        huoliHudieBtn = new QPushButton(tab_4);
        huoliHudieBtn->setObjectName(QStringLiteral("huoliHudieBtn"));
        huoliHudieBtn->setGeometry(QRect(80, 100, 41, 23));
        huoliCanglangBtn = new QPushButton(tab_4);
        huoliCanglangBtn->setObjectName(QStringLiteral("huoliCanglangBtn"));
        huoliCanglangBtn->setGeometry(QRect(80, 120, 41, 23));
        juediBtn = new QPushButton(tab_4);
        juediBtn->setObjectName(QStringLiteral("juediBtn"));
        juediBtn->setGeometry(QRect(120, 0, 41, 23));
        wanshengBtn = new QPushButton(tab_4);
        wanshengBtn->setObjectName(QStringLiteral("wanshengBtn"));
        wanshengBtn->setGeometry(QRect(120, 20, 41, 23));
        guaguaBtn = new QPushButton(tab_4);
        guaguaBtn->setObjectName(QStringLiteral("guaguaBtn"));
        guaguaBtn->setGeometry(QRect(120, 40, 41, 23));
        yunshiBtn = new QPushButton(tab_4);
        yunshiBtn->setObjectName(QStringLiteral("yunshiBtn"));
        yunshiBtn->setGeometry(QRect(120, 60, 41, 23));
        huoliWeijiBtn = new QPushButton(tab_4);
        huoliWeijiBtn->setObjectName(QStringLiteral("huoliWeijiBtn"));
        huoliWeijiBtn->setGeometry(QRect(120, 120, 41, 23));
        huoliJingjiiBtn = new QPushButton(tab_4);
        huoliJingjiiBtn->setObjectName(QStringLiteral("huoliJingjiiBtn"));
        huoliJingjiiBtn->setGeometry(QRect(120, 100, 41, 23));
        huoliWuxingBtn = new QPushButton(tab_4);
        huoliWuxingBtn->setObjectName(QStringLiteral("huoliWuxingBtn"));
        huoliWuxingBtn->setGeometry(QRect(160, 0, 41, 23));
        tabWidget_2->addTab(tab_4, QString());
        tab_5 = new QWidget();
        tab_5->setObjectName(QStringLiteral("tab_5"));
        dengsaoBtn = new QPushButton(tab_5);
        dengsaoBtn->setObjectName(QStringLiteral("dengsaoBtn"));
        dengsaoBtn->setGeometry(QRect(0, 0, 41, 23));
        shangjiaBtn = new QPushButton(tab_5);
        shangjiaBtn->setObjectName(QStringLiteral("shangjiaBtn"));
        shangjiaBtn->setGeometry(QRect(0, 40, 41, 23));
        xuanquBtn = new QPushButton(tab_5);
        xuanquBtn->setObjectName(QStringLiteral("xuanquBtn"));
        xuanquBtn->setGeometry(QRect(0, 20, 41, 23));
        xiajiaBtn = new QPushButton(tab_5);
        xiajiaBtn->setObjectName(QStringLiteral("xiajiaBtn"));
        xiajiaBtn->setGeometry(QRect(0, 60, 41, 23));
        qingbaoBtn = new QPushButton(tab_5);
        qingbaoBtn->setObjectName(QStringLiteral("qingbaoBtn"));
        qingbaoBtn->setGeometry(QRect(0, 80, 41, 23));
        pingbiBtn = new QPushButton(tab_5);
        pingbiBtn->setObjectName(QStringLiteral("pingbiBtn"));
        pingbiBtn->setGeometry(QRect(0, 100, 41, 23));
        huoyueLingJiangBtn = new QPushButton(tab_5);
        huoyueLingJiangBtn->setObjectName(QStringLiteral("huoyueLingJiangBtn"));
        huoyueLingJiangBtn->setGeometry(QRect(0, 120, 41, 23));
        xiuliBtn = new QPushButton(tab_5);
        xiuliBtn->setObjectName(QStringLiteral("xiuliBtn"));
        xiuliBtn->setGeometry(QRect(40, 0, 41, 23));
        shengjiBtn = new QPushButton(tab_5);
        shengjiBtn->setObjectName(QStringLiteral("shengjiBtn"));
        shengjiBtn->setGeometry(QRect(40, 20, 41, 23));
        jiadianBtn = new QPushButton(tab_5);
        jiadianBtn->setObjectName(QStringLiteral("jiadianBtn"));
        jiadianBtn->setGeometry(QRect(40, 40, 41, 23));
        lingyouBtn = new QPushButton(tab_5);
        lingyouBtn->setObjectName(QStringLiteral("lingyouBtn"));
        lingyouBtn->setGeometry(QRect(40, 60, 41, 23));
        shengmaBtn = new QPushButton(tab_5);
        shengmaBtn->setObjectName(QStringLiteral("shengmaBtn"));
        shengmaBtn->setGeometry(QRect(40, 80, 41, 23));
        tongjiCailiaoBtn = new QPushButton(tab_5);
        tongjiCailiaoBtn->setObjectName(QStringLiteral("tongjiCailiaoBtn"));
        tongjiCailiaoBtn->setGeometry(QRect(40, 100, 41, 23));
        lingFuliBtn = new QPushButton(tab_5);
        lingFuliBtn->setObjectName(QStringLiteral("lingFuliBtn"));
        lingFuliBtn->setGeometry(QRect(40, 120, 41, 23));
        jinHJunBtn = new QPushButton(tab_5);
        jinHJunBtn->setObjectName(QStringLiteral("jinHJunBtn"));
        jinHJunBtn->setGeometry(QRect(80, 0, 41, 23));
        sahuoBtn = new QPushButton(tab_5);
        sahuoBtn->setObjectName(QStringLiteral("sahuoBtn"));
        sahuoBtn->setGeometry(QRect(80, 20, 41, 23));
        cuncangBtn = new QPushButton(tab_5);
        cuncangBtn->setObjectName(QStringLiteral("cuncangBtn"));
        cuncangBtn->setGeometry(QRect(80, 40, 41, 23));
        chongwuShoumingBtn = new QPushButton(tab_5);
        chongwuShoumingBtn->setObjectName(QStringLiteral("chongwuShoumingBtn"));
        chongwuShoumingBtn->setGeometry(QRect(80, 60, 41, 23));
        powerCheckBtn = new QPushButton(tab_5);
        powerCheckBtn->setObjectName(QStringLiteral("powerCheckBtn"));
        powerCheckBtn->setGeometry(QRect(80, 80, 41, 23));
        joinForceBtn = new QPushButton(tab_5);
        joinForceBtn->setObjectName(QStringLiteral("joinForceBtn"));
        joinForceBtn->setGeometry(QRect(80, 100, 41, 23));
        jiaoxueqiuBtn = new QPushButton(tab_5);
        jiaoxueqiuBtn->setObjectName(QStringLiteral("jiaoxueqiuBtn"));
        jiaoxueqiuBtn->setGeometry(QRect(180, 0, 41, 23));
        embededScriptBtn = new QPushButton(tab_5);
        embededScriptBtn->setObjectName(QStringLiteral("embededScriptBtn"));
        embededScriptBtn->setGeometry(QRect(180, 120, 41, 23));
        kaibaoBtn = new QPushButton(tab_5);
        kaibaoBtn->setObjectName(QStringLiteral("kaibaoBtn"));
        kaibaoBtn->setGeometry(QRect(180, 20, 41, 23));
        tabWidget_2->addTab(tab_5, QString());
        tab_12 = new QWidget();
        tab_12->setObjectName(QStringLiteral("tab_12"));
        goldCalculate = new QPushButton(tab_12);
        goldCalculate->setObjectName(QStringLiteral("goldCalculate"));
        goldCalculate->setGeometry(QRect(10, 10, 75, 23));
        test = new QLineEdit(tab_12);
        test->setObjectName(QStringLiteral("test"));
        test->setGeometry(QRect(10, 40, 191, 20));
        shengdanBtn = new QPushButton(tab_12);
        shengdanBtn->setObjectName(QStringLiteral("shengdanBtn"));
        shengdanBtn->setGeometry(QRect(90, 10, 75, 23));
        idField = new QLineEdit(tab_12);
        idField->setObjectName(QStringLiteral("idField"));
        idField->setGeometry(QRect(10, 70, 191, 20));
        tabWidget_2->addTab(tab_12, QString());
        scriptUp = new QPushButton(groupBox_5);
        scriptUp->setObjectName(QStringLiteral("scriptUp"));
        scriptUp->setGeometry(QRect(90, 20, 21, 41));
        scriptDown = new QPushButton(groupBox_5);
        scriptDown->setObjectName(QStringLiteral("scriptDown"));
        scriptDown->setGeometry(QRect(90, 60, 21, 41));
        scriptDelete = new QPushButton(groupBox_5);
        scriptDelete->setObjectName(QStringLiteral("scriptDelete"));
        scriptDelete->setGeometry(QRect(90, 100, 21, 41));
        scriptClear = new QPushButton(groupBox_5);
        scriptClear->setObjectName(QStringLiteral("scriptClear"));
        scriptClear->setGeometry(QRect(90, 140, 21, 41));
        groupBox_11 = new QGroupBox(tab_3);
        groupBox_11->setObjectName(QStringLiteral("groupBox_11"));
        groupBox_11->setGeometry(QRect(10, 210, 381, 201));
        subScriptSortList = new QListWidget(groupBox_11);
        subScriptSortList->setObjectName(QStringLiteral("subScriptSortList"));
        subScriptSortList->setGeometry(QRect(10, 30, 81, 161));
        scriptClear_2 = new QPushButton(groupBox_11);
        scriptClear_2->setObjectName(QStringLiteral("scriptClear_2"));
        scriptClear_2->setGeometry(QRect(90, 150, 21, 41));
        scriptDown_2 = new QPushButton(groupBox_11);
        scriptDown_2->setObjectName(QStringLiteral("scriptDown_2"));
        scriptDown_2->setGeometry(QRect(90, 70, 21, 41));
        scriptDelete_2 = new QPushButton(groupBox_11);
        scriptDelete_2->setObjectName(QStringLiteral("scriptDelete_2"));
        scriptDelete_2->setGeometry(QRect(90, 110, 21, 41));
        scriptUp_2 = new QPushButton(groupBox_11);
        scriptUp_2->setObjectName(QStringLiteral("scriptUp_2"));
        scriptUp_2->setGeometry(QRect(90, 30, 21, 41));
        tabWidget_4 = new QTabWidget(groupBox_11);
        tabWidget_4->setObjectName(QStringLiteral("tabWidget_4"));
        tabWidget_4->setGeometry(QRect(120, 30, 101, 161));
        tab_13 = new QWidget();
        tab_13->setObjectName(QStringLiteral("tab_13"));
        zuduiBtn = new QPushButton(tab_13);
        zuduiBtn->setObjectName(QStringLiteral("zuduiBtn"));
        zuduiBtn->setGeometry(QRect(0, 0, 41, 23));
        jiaoyouBtn = new QPushButton(tab_13);
        jiaoyouBtn->setObjectName(QStringLiteral("jiaoyouBtn"));
        jiaoyouBtn->setGeometry(QRect(0, 20, 41, 23));
        alineBtn = new QPushButton(tab_13);
        alineBtn->setObjectName(QStringLiteral("alineBtn"));
        alineBtn->setGeometry(QRect(0, 40, 41, 23));
        teamMitanbtn = new QPushButton(tab_13);
        teamMitanbtn->setObjectName(QStringLiteral("teamMitanbtn"));
        teamMitanbtn->setGeometry(QRect(0, 60, 41, 23));
        teamPatabtn = new QPushButton(tab_13);
        teamPatabtn->setObjectName(QStringLiteral("teamPatabtn"));
        teamPatabtn->setGeometry(QRect(0, 80, 41, 23));
        tabWidget_4->addTab(tab_13, QString());
        tab_14 = new QWidget();
        tab_14->setObjectName(QStringLiteral("tab_14"));
        tabWidget_4->addTab(tab_14, QString());
        groupBox_12 = new QGroupBox(groupBox_11);
        groupBox_12->setObjectName(QStringLiteral("groupBox_12"));
        groupBox_12->setGeometry(QRect(240, 20, 131, 171));
        checkBox = new QCheckBox(groupBox_12);
        checkBox->setObjectName(QStringLiteral("checkBox"));
        checkBox->setGeometry(QRect(10, 20, 101, 16));
        teamSpinBox = new QSpinBox(groupBox_12);
        teamSpinBox->setObjectName(QStringLiteral("teamSpinBox"));
        teamSpinBox->setGeometry(QRect(80, 40, 42, 22));
        teamSpinBox->setMinimum(1);
        teamSpinBox->setMaximum(5);
        teamSpinBox->setValue(2);
        label_8 = new QLabel(groupBox_12);
        label_8->setObjectName(QStringLiteral("label_8"));
        label_8->setGeometry(QRect(10, 50, 54, 12));
        tabWidget_3->addTab(tab_3, QString());
        ControllerFrameEx->setCentralWidget(centralWidget);
        tabWidget_3->raise();
        tableWidget->raise();
        groupBox->raise();
        groupBox_2->raise();
        pathSelectBTN->raise();
        gamePathEditor->raise();
        groupBox_6->raise();
        menuBar = new QMenuBar(ControllerFrameEx);
        menuBar->setObjectName(QStringLiteral("menuBar"));
        menuBar->setGeometry(QRect(0, 0, 1075, 23));
        ControllerFrameEx->setMenuBar(menuBar);
        mainToolBar = new QToolBar(ControllerFrameEx);
        mainToolBar->setObjectName(QStringLiteral("mainToolBar"));
        ControllerFrameEx->addToolBar(Qt::TopToolBarArea, mainToolBar);
        statusBar = new QStatusBar(ControllerFrameEx);
        statusBar->setObjectName(QStringLiteral("statusBar"));
        ControllerFrameEx->setStatusBar(statusBar);

        retranslateUi(ControllerFrameEx);
        QObject::connect(tableWidget, SIGNAL(customContextMenuRequested(QPoint)), ControllerFrameEx, SLOT(onRightClicked(QPoint)));
        QObject::connect(pathSelectBTN, SIGNAL(clicked()), ControllerFrameEx, SLOT(pathBtnClicked()));

        tabWidget_3->setCurrentIndex(0);
        tabWidget->setCurrentIndex(0);
        defaultTab->setCurrentIndex(0);
        tabWidget_5->setCurrentIndex(0);
        tabWidget_2->setCurrentIndex(0);
        tabWidget_4->setCurrentIndex(0);


        QMetaObject::connectSlotsByName(ControllerFrameEx);
    } // setupUi

    void retranslateUi(QMainWindow *ControllerFrameEx)
    {
        ControllerFrameEx->setWindowTitle(QApplication::translate("ControllerFrameEx", "ASDDFa", Q_NULLPTR));
        groupBox->setTitle(QApplication::translate("ControllerFrameEx", "\345\214\272\346\234\215\350\256\276\347\275\256", Q_NULLPTR));
        zoneRadio1->setText(QApplication::translate("ControllerFrameEx", "\344\270\200\347\273\237", Q_NULLPTR));
        zoneRadio2->setText(QApplication::translate("ControllerFrameEx", "\345\215\216\345\244\217", Q_NULLPTR));
        label->setText(QApplication::translate("ControllerFrameEx", "\350\256\276\347\275\256\345\214\272\345\217\267", Q_NULLPTR));
        groupBox_2->setTitle(QApplication::translate("ControllerFrameEx", "\350\247\222\350\211\262\350\256\276\347\275\256", Q_NULLPTR));
        autoCRole->setText(QApplication::translate("ControllerFrameEx", "\346\230\257\345\220\246\350\207\252\345\212\250\346\215\242\345\217\267", Q_NULLPTR));
        autoLogin->setText(QApplication::translate("ControllerFrameEx", "\346\230\257\345\220\246\345\207\214\346\231\250\351\207\215\347\275\256", Q_NULLPTR));
        label_6->setText(QApplication::translate("ControllerFrameEx", "\350\246\201\345\207\240\344\270\252\345\260\217\346\234\213\345\217\213\357\274\232", Q_NULLPTR));
        pathSelectBTN->setText(QApplication::translate("ControllerFrameEx", "\350\267\257\345\276\204\351\200\211\346\213\251", Q_NULLPTR));
        groupBox_6->setTitle(QApplication::translate("ControllerFrameEx", "\351\205\215\347\275\256\347\256\241\347\220\206", Q_NULLPTR));
        readBtn1->setText(QApplication::translate("ControllerFrameEx", "\350\257\273\344\270\200", Q_NULLPTR));
        readBtn2->setText(QApplication::translate("ControllerFrameEx", "\350\257\273\344\272\214", Q_NULLPTR));
        readBtn3->setText(QApplication::translate("ControllerFrameEx", "\350\257\273\344\270\211", Q_NULLPTR));
        readBtn4->setText(QApplication::translate("ControllerFrameEx", "\350\257\273\345\233\233", Q_NULLPTR));
        readBtn5->setText(QApplication::translate("ControllerFrameEx", "\350\257\273\344\272\224", Q_NULLPTR));
        readBtn6->setText(QApplication::translate("ControllerFrameEx", "\350\257\273\345\205\255", Q_NULLPTR));
        writeBtn2->setText(QApplication::translate("ControllerFrameEx", "\345\206\231\344\272\214", Q_NULLPTR));
        writeBtn4->setText(QApplication::translate("ControllerFrameEx", "\345\206\231\345\233\233", Q_NULLPTR));
        writeBtn5->setText(QApplication::translate("ControllerFrameEx", "\345\206\231\344\272\224", Q_NULLPTR));
        writeBtn3->setText(QApplication::translate("ControllerFrameEx", "\345\206\231\344\270\211", Q_NULLPTR));
        writeBtn1->setText(QApplication::translate("ControllerFrameEx", "\345\206\231\344\270\200", Q_NULLPTR));
        writeBtn6->setText(QApplication::translate("ControllerFrameEx", "\345\206\231\345\205\255", Q_NULLPTR));
        baseConfigBtn->setText(QApplication::translate("ControllerFrameEx", "\344\277\235\345\255\230\n"
"\345\275\223\345\211\215", Q_NULLPTR));
        groupBox_3->setTitle(QApplication::translate("ControllerFrameEx", "\345\220\257\345\212\250\345\222\214\345\205\263\351\227\255", Q_NULLPTR));
        openLag->setText(QApplication::translate("ControllerFrameEx", "\345\274\200\345\220\257\345\273\266\350\277\237(\347\247\222)", Q_NULLPTR));
        label_2->setText(QApplication::translate("ControllerFrameEx", "\344\270\200\346\254\241\345\274\200\345\220\257\346\225\260\351\207\217", Q_NULLPTR));
        onePunch->setText(QApplication::translate("ControllerFrameEx", "\344\270\200\351\224\256\345\220\257\345\212\250", Q_NULLPTR));
        engineBtn->setText(QApplication::translate("ControllerFrameEx", "engine", Q_NULLPTR));
        EnginedBox->setText(QApplication::translate("ControllerFrameEx", "SingleCode", Q_NULLPTR));
        tabWidget->setTabText(tabWidget->indexOf(tab), QApplication::translate("ControllerFrameEx", "\350\207\252\345\212\250\347\273\221\345\256\232", Q_NULLPTR));
        tabWidget->setTabText(tabWidget->indexOf(tab_2), QApplication::translate("ControllerFrameEx", "\346\211\213\345\212\250\347\273\221\345\256\232", Q_NULLPTR));
        generalEnd->setText(QApplication::translate("ControllerFrameEx", "\344\270\200\350\210\254\347\273\223\346\235\237", Q_NULLPTR));
        forceEnd->setText(QApplication::translate("ControllerFrameEx", "\345\274\272\345\210\266\347\273\223\346\235\237", Q_NULLPTR));
        label_61->setText(QApplication::translate("ControllerFrameEx", "\345\211\251\344\275\231\346\227\266\351\227\264\357\274\232", Q_NULLPTR));
        timeLabel->setText(QApplication::translate("ControllerFrameEx", "00", Q_NULLPTR));
        label_7->setText(QApplication::translate("ControllerFrameEx", "\345\210\206\351\222\237", Q_NULLPTR));
        groupBox_4->setTitle(QApplication::translate("ControllerFrameEx", "\345\237\272\346\234\254\350\256\276\347\275\256", Q_NULLPTR));
        isZhuxianEnableBox->setText(QApplication::translate("ControllerFrameEx", "\346\230\257\345\220\246\344\270\273\347\272\277", Q_NULLPTR));
        captainBox->setText(QApplication::translate("ControllerFrameEx", "\350\207\252\345\212\250\351\230\237\351\225\277", Q_NULLPTR));
        huoliProtectBox->setText(QApplication::translate("ControllerFrameEx", "\346\264\273\345\212\233\344\277\235\346\212\244", Q_NULLPTR));
        buqianBox->setText(QApplication::translate("ControllerFrameEx", "\350\241\245\347\255\276", Q_NULLPTR));
        junziShiyongBox->setText(QApplication::translate("ControllerFrameEx", "\346\230\257\345\220\246\347\224\250\350\217\214", Q_NULLPTR));
        shimenYongjunBox->setText(QApplication::translate("ControllerFrameEx", "\346\230\257\345\220\246\345\270\210\351\227\250\344\271\260\347\211\251", Q_NULLPTR));
        label_71->setText(QApplication::translate("ControllerFrameEx", "\346\273\241\346\264\273\345\217\202\346\225\260\357\274\232", Q_NULLPTR));
        label_9->setText(QApplication::translate("ControllerFrameEx", "\345\212\277\345\212\233ID:", Q_NULLPTR));
        label_10->setText(QApplication::translate("ControllerFrameEx", "\350\266\205\346\227\266\350\267\263\350\277\207", Q_NULLPTR));
        label_11->setText(QApplication::translate("ControllerFrameEx", "\345\210\206\351\222\237", Q_NULLPTR));
        label_12->setText(QApplication::translate("ControllerFrameEx", "\345\257\206\346\216\242\345\276\252\347\216\257\346\254\241\346\225\260\357\274\232", Q_NULLPTR));
        label_13->setText(QApplication::translate("ControllerFrameEx", "\344\270\273\347\272\277\345\201\234\346\255\242\347\255\211\347\272\247\357\274\232", Q_NULLPTR));
        label_14->setText(QApplication::translate("ControllerFrameEx", "\345\270\210\351\227\250\345\276\252\347\216\257\346\254\241\346\225\260\357\274\232", Q_NULLPTR));
        huoyueCheckBox->setText(QApplication::translate("ControllerFrameEx", "\346\230\257\345\220\246\346\264\273\345\212\233\346\243\200\346\237\245", Q_NULLPTR));
        generalDZCheckBox->setText(QApplication::translate("ControllerFrameEx", "\345\256\232\345\277\227\345\260\206\345\206\233\345\244\261\350\270\252", Q_NULLPTR));
        defaultTab->setTabText(defaultTab->indexOf(tab_6), QApplication::translate("ControllerFrameEx", "\345\237\272", Q_NULLPTR));
        groupBox_7->setTitle(QApplication::translate("ControllerFrameEx", "MY", Q_NULLPTR));
        mengyanRadio1->setText(QApplication::translate("ControllerFrameEx", "Shang", Q_NULLPTR));
        mengyanRadio2->setText(QApplication::translate("ControllerFrameEx", "Xia", Q_NULLPTR));
        groupBox_8->setTitle(QApplication::translate("ControllerFrameEx", "JD", Q_NULLPTR));
        jiandingRadio1->setText(QApplication::translate("ControllerFrameEx", "Shang", Q_NULLPTR));
        jiandingRadio2->setText(QApplication::translate("ControllerFrameEx", "Xia", Q_NULLPTR));
        groupBox_9->setTitle(QApplication::translate("ControllerFrameEx", "JD", Q_NULLPTR));
        jiandingRadio1_2->setText(QApplication::translate("ControllerFrameEx", "Shang", Q_NULLPTR));
        jiandingRadio2_2->setText(QApplication::translate("ControllerFrameEx", "Xia", Q_NULLPTR));
        groupBox_10->setTitle(QApplication::translate("ControllerFrameEx", "7C", Q_NULLPTR));
        qicaiRadio1->setText(QApplication::translate("ControllerFrameEx", "Shang", Q_NULLPTR));
        qicaiRadio2->setText(QApplication::translate("ControllerFrameEx", "Xia", Q_NULLPTR));
        defaultTab->setTabText(defaultTab->indexOf(tab_7), QApplication::translate("ControllerFrameEx", "\347\273\206", Q_NULLPTR));
        defaultTab->setTabText(defaultTab->indexOf(tab_8), QApplication::translate("ControllerFrameEx", "\351\207\221\345\206\233", Q_NULLPTR));
        saoComboBox->setCurrentText(QString());
        goldController->setText(QApplication::translate("ControllerFrameEx", "100000", Q_NULLPTR));
        label_3->setText(QApplication::translate("ControllerFrameEx", "<html><head/><body><p>\344\272\272\347\211\251\345\206\233\345\244\247\344\272\216\344\270\215\346\211\253\357\274\232</p></body></html>", Q_NULLPTR));
        label_4->setText(QApplication::translate("ControllerFrameEx", "\345\215\225\344\273\267\345\244\247\344\272\216\344\270\215\346\211\253\357\274\232", Q_NULLPTR));
        safeJunzi->setText(QApplication::translate("ControllerFrameEx", "17000", Q_NULLPTR));
        label_5->setText(QApplication::translate("ControllerFrameEx", "\346\214\207\345\256\232\344\275\215\347\275\256:", Q_NULLPTR));
        defaultTab->setTabText(defaultTab->indexOf(tab_9), QApplication::translate("ControllerFrameEx", "\346\211\253", Q_NULLPTR));
        tabWidget_3->setTabText(tabWidget_3->indexOf(tab_10), QApplication::translate("ControllerFrameEx", "\345\220\257\345\212\250", Q_NULLPTR));
        rizuanBox->setText(QApplication::translate("ControllerFrameEx", "\346\227\245\351\222\273", Q_NULLPTR));
        yuezuanBox->setText(QApplication::translate("ControllerFrameEx", "\346\234\210\351\222\273", Q_NULLPTR));
        liuyaoBox->setText(QApplication::translate("ControllerFrameEx", "\345\205\255\347\210\273", Q_NULLPTR));
        tabWidget_5->setTabText(tabWidget_5->indexOf(tab_15), QApplication::translate("ControllerFrameEx", "\346\270\205\345\214\205", Q_NULLPTR));
        tabWidget_5->setTabText(tabWidget_5->indexOf(tab_16), QApplication::translate("ControllerFrameEx", "\344\273\223\345\272\223", Q_NULLPTR));
        tabWidget_3->setTabText(tabWidget_3->indexOf(tab_11), QApplication::translate("ControllerFrameEx", "\351\253\230\347\272\247\350\256\276\347\275\256", Q_NULLPTR));
        groupBox_5->setTitle(QApplication::translate("ControllerFrameEx", "\350\204\232\346\234\254\350\256\276\347\275\256", Q_NULLPTR));
        guaitiBtn->setText(QApplication::translate("ControllerFrameEx", "\346\200\252\351\242\230", Q_NULLPTR));
        xiangshiBtn->setText(QApplication::translate("ControllerFrameEx", "\344\271\241\350\257\225", Q_NULLPTR));
        mitanBtn->setText(QApplication::translate("ControllerFrameEx", "\345\257\206\346\216\242", Q_NULLPTR));
        shimenBtn->setText(QApplication::translate("ControllerFrameEx", "\345\270\210\351\227\250", Q_NULLPTR));
        wuxingBtn->setText(QApplication::translate("ControllerFrameEx", "\344\272\224\350\241\214", Q_NULLPTR));
        chumoBtn->setText(QApplication::translate("ControllerFrameEx", "\351\231\244\351\255\224", Q_NULLPTR));
        zhufuBtn->setText(QApplication::translate("ControllerFrameEx", "\347\245\235\347\246\217", Q_NULLPTR));
        shiliBtn->setText(QApplication::translate("ControllerFrameEx", "\345\212\277\344\273\273", Q_NULLPTR));
        wuwaBtn->setText(QApplication::translate("ControllerFrameEx", "\344\272\224\346\214\226", Q_NULLPTR));
        kuaimaBtn->setText(QApplication::translate("ControllerFrameEx", "\345\277\253\351\251\254", Q_NULLPTR));
        mijingBtn->setText(QApplication::translate("ControllerFrameEx", "\347\247\230\345\242\203", Q_NULLPTR));
        tianlaoBtn->setText(QApplication::translate("ControllerFrameEx", "\345\244\251\346\270\212", Q_NULLPTR));
        biwuBtn->setText(QApplication::translate("ControllerFrameEx", "\346\257\224\346\255\246", Q_NULLPTR));
        xiaoyaoBtn->setText(QApplication::translate("ControllerFrameEx", "\346\264\273\351\201\245", Q_NULLPTR));
        yanwuBtn->setText(QApplication::translate("ControllerFrameEx", "\346\274\224\346\255\246", Q_NULLPTR));
        tianweiBtn->setText(QApplication::translate("ControllerFrameEx", "\345\244\251\345\215\261", Q_NULLPTR));
        jingjiBtn->setText(QApplication::translate("ControllerFrameEx", "\347\253\236\346\212\200", Q_NULLPTR));
        huoliXiangyaoBtn->setText(QApplication::translate("ControllerFrameEx", "\346\264\273\345\246\226", Q_NULLPTR));
        huoliHuangquanBtn->setText(QApplication::translate("ControllerFrameEx", "\346\264\273\351\273\204", Q_NULLPTR));
        huoliHudieBtn->setText(QApplication::translate("ControllerFrameEx", "\346\264\273\350\203\241", Q_NULLPTR));
        huoliCanglangBtn->setText(QApplication::translate("ControllerFrameEx", "\346\264\273\344\273\223", Q_NULLPTR));
        juediBtn->setText(QApplication::translate("ControllerFrameEx", "\345\206\263\345\215\207", Q_NULLPTR));
        wanshengBtn->setText(QApplication::translate("ControllerFrameEx", "\344\270\207\347\233\233", Q_NULLPTR));
        guaguaBtn->setText(QApplication::translate("ControllerFrameEx", "\345\221\261\345\221\261", Q_NULLPTR));
        yunshiBtn->setText(QApplication::translate("ControllerFrameEx", "\350\277\220\345\212\277", Q_NULLPTR));
        huoliWeijiBtn->setText(QApplication::translate("ControllerFrameEx", "\346\264\273\345\215\261", Q_NULLPTR));
        huoliJingjiiBtn->setText(QApplication::translate("ControllerFrameEx", "\346\264\273\345\267\205", Q_NULLPTR));
        huoliWuxingBtn->setText(QApplication::translate("ControllerFrameEx", "\346\264\273\344\272\224", Q_NULLPTR));
        tabWidget_2->setTabText(tabWidget_2->indexOf(tab_4), QApplication::translate("ControllerFrameEx", "\346\227\245\345\270\270", Q_NULLPTR));
        dengsaoBtn->setText(QApplication::translate("ControllerFrameEx", "\347\255\211\346\211\253", Q_NULLPTR));
        shangjiaBtn->setText(QApplication::translate("ControllerFrameEx", "\344\270\212\346\236\266", Q_NULLPTR));
        xuanquBtn->setText(QApplication::translate("ControllerFrameEx", "\351\200\211\345\214\272", Q_NULLPTR));
        xiajiaBtn->setText(QApplication::translate("ControllerFrameEx", "\344\270\213\346\236\266", Q_NULLPTR));
        qingbaoBtn->setText(QApplication::translate("ControllerFrameEx", "\346\270\205\345\214\205", Q_NULLPTR));
        pingbiBtn->setText(QApplication::translate("ControllerFrameEx", "\345\261\217\350\224\275", Q_NULLPTR));
        huoyueLingJiangBtn->setText(QApplication::translate("ControllerFrameEx", "\346\264\273\350\222\213", Q_NULLPTR));
        xiuliBtn->setText(QApplication::translate("ControllerFrameEx", "\344\277\256\350\272\253", Q_NULLPTR));
        shengjiBtn->setText(QApplication::translate("ControllerFrameEx", "\345\215\207\346\212\200", Q_NULLPTR));
        jiadianBtn->setText(QApplication::translate("ControllerFrameEx", "\345\215\207\347\202\271", Q_NULLPTR));
        lingyouBtn->setText(QApplication::translate("ControllerFrameEx", "\351\242\206\351\202\256", Q_NULLPTR));
        shengmaBtn->setText(QApplication::translate("ControllerFrameEx", "\345\215\207\351\251\254", Q_NULLPTR));
        tongjiCailiaoBtn->setText(QApplication::translate("ControllerFrameEx", "\347\273\237\346\211\215", Q_NULLPTR));
        lingFuliBtn->setText(QApplication::translate("ControllerFrameEx", "\351\242\206\347\246\217", Q_NULLPTR));
        jinHJunBtn->setText(QApplication::translate("ControllerFrameEx", "\351\207\221\345\206\233", Q_NULLPTR));
        sahuoBtn->setText(QApplication::translate("ControllerFrameEx", "\346\211\253\345\225\212", Q_NULLPTR));
        cuncangBtn->setText(QApplication::translate("ControllerFrameEx", "\345\255\230\344\273\223", Q_NULLPTR));
        chongwuShoumingBtn->setText(QApplication::translate("ControllerFrameEx", "\345\256\240\345\257\277", Q_NULLPTR));
        powerCheckBtn->setText(QApplication::translate("ControllerFrameEx", "\346\264\273\346\237\245", Q_NULLPTR));
        joinForceBtn->setText(QApplication::translate("ControllerFrameEx", "\345\212\240\345\212\277", Q_NULLPTR));
        jiaoxueqiuBtn->setText(QApplication::translate("ControllerFrameEx", "\345\240\206\351\233\252", Q_NULLPTR));
        embededScriptBtn->setText(QApplication::translate("ControllerFrameEx", "\345\255\220\346\234\254", Q_NULLPTR));
        kaibaoBtn->setText(QApplication::translate("ControllerFrameEx", "\345\274\200\345\214\205", Q_NULLPTR));
        tabWidget_2->setTabText(tabWidget_2->indexOf(tab_5), QApplication::translate("ControllerFrameEx", "\345\212\237\350\203\275", Q_NULLPTR));
        goldCalculate->setText(QApplication::translate("ControllerFrameEx", "\345\206\233\350\265\204\346\200\273\350\256\241", Q_NULLPTR));
        shengdanBtn->setText(QApplication::translate("ControllerFrameEx", "\345\234\243\350\257\236\351\233\252\347\220\203", Q_NULLPTR));
        tabWidget_2->setTabText(tabWidget_2->indexOf(tab_12), QApplication::translate("ControllerFrameEx", "\345\277\253\351\200\237\351\205\215\347\275\256", Q_NULLPTR));
        scriptUp->setText(QApplication::translate("ControllerFrameEx", "\344\270\212", Q_NULLPTR));
        scriptDown->setText(QApplication::translate("ControllerFrameEx", "\344\270\213", Q_NULLPTR));
        scriptDelete->setText(QApplication::translate("ControllerFrameEx", "\345\210\240", Q_NULLPTR));
        scriptClear->setText(QApplication::translate("ControllerFrameEx", "\346\270\205", Q_NULLPTR));
        groupBox_11->setTitle(QApplication::translate("ControllerFrameEx", "\345\255\220\350\204\232\346\234\254\350\256\276\347\275\256", Q_NULLPTR));
        scriptClear_2->setText(QApplication::translate("ControllerFrameEx", "\346\270\205", Q_NULLPTR));
        scriptDown_2->setText(QApplication::translate("ControllerFrameEx", "\344\270\213", Q_NULLPTR));
        scriptDelete_2->setText(QApplication::translate("ControllerFrameEx", "\345\210\240", Q_NULLPTR));
        scriptUp_2->setText(QApplication::translate("ControllerFrameEx", "\344\270\212", Q_NULLPTR));
        zuduiBtn->setText(QApplication::translate("ControllerFrameEx", "\347\273\204\351\230\237", Q_NULLPTR));
        jiaoyouBtn->setText(QApplication::translate("ControllerFrameEx", "\344\272\244\345\217\213", Q_NULLPTR));
        alineBtn->setText(QApplication::translate("ControllerFrameEx", "\345\257\271\351\275\220", Q_NULLPTR));
        teamMitanbtn->setText(QApplication::translate("ControllerFrameEx", "\351\230\237\345\257\206", Q_NULLPTR));
        teamPatabtn->setText(QApplication::translate("ControllerFrameEx", "\347\210\254\345\241\224", Q_NULLPTR));
        tabWidget_4->setTabText(tabWidget_4->indexOf(tab_13), QApplication::translate("ControllerFrameEx", "\345\212\237\350\203\275", Q_NULLPTR));
        tabWidget_4->setTabText(tabWidget_4->indexOf(tab_14), QApplication::translate("ControllerFrameEx", "\345\211\257\346\234\254", Q_NULLPTR));
        groupBox_12->setTitle(QApplication::translate("ControllerFrameEx", "\351\200\211\351\241\271", Q_NULLPTR));
        checkBox->setText(QApplication::translate("ControllerFrameEx", "\346\230\257\345\220\246\345\215\225\347\213\254\345\276\252\347\216\257", Q_NULLPTR));
        label_8->setText(QApplication::translate("ControllerFrameEx", "\351\230\237\351\225\277\345\217\202\346\225\260\357\274\232", Q_NULLPTR));
        tabWidget_3->setTabText(tabWidget_3->indexOf(tab_3), QApplication::translate("ControllerFrameEx", "\350\204\232\346\234\254\346\265\201\347\250\213", Q_NULLPTR));
    } // retranslateUi

};

namespace Ui {
    class ControllerFrameEx: public Ui_ControllerFrameEx {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_CONTROLLERFRAMEEX_H
